### ISSUE TITLE
Consider adding package-lock.json file for easier time deploying

### ISSUE THREAD

**Issue by skywarth** [GeorgeGUS/my-calendar#1]
Hi there,

I've seen that you've used [Vite Github Pages Deployer](https://github.com/skywarth/vite-github-pages-deployer) and encountered some error while using it.

[In this action run](https://github.com/GeorgeGUS/my-calendar/actions/runs/7366441771/job/20048708507) you received an error from `npm`, indicating "The `npm ci` command can only install with an existing `package-lock.json`". This is due to the fact that my package used `npm ci` to install the project dependencies, this is the designated method for CI installations. You may resolve this issue by simply uploading `package-lock.json` in your repository, you may have it in gitignore atm.

Documentation also has a description on how to identify and resolve this error: https://github.com/skywarth/vite-github-pages-deployer#63-package-lockjson-is-not-present-when-using-npm-as-package-manager-preferrence

Hope it helps.

**Comment by GeorgeGUS** [comment]
Hi @skywarth !

Thanks for your reply. I'm only using an `yarn` installer with it's own `yarn.lock` file. I've [already solved](https://github.com/GeorgeGUS/my-calendar/actions/runs/7366507866/job/20048838771) the problem by switching to `actions/deploy-pages@v2`. Is there some benefits to using your deploy action instead that one? If there is not, I think I will continue to use current solution :)

**Comment by skywarth** [comment]
The action package supports range of configurations and settings that might come in handy. Moreover, it is also compatible with `yarn`, simply providing input parameter `package_manager=yarn` is sufficient, it installs the dependencies by issuing `yarn install --immutable --immutable-cache --check-cache` which takes `yarn.lock` into account AFAIK. 

I suppose documentation was slightly lacking if it wasn't clear. But I'm happy that you resolved it by implementing your own action pipeline. Cheers.
